
package principal;

import appspv22i.AppSPV22i;
import Evaluaciones.*;
import java.awt.Dimension;
import vista.*;



public class mdiSPV22i extends javax.swing.JFrame {

    
    public mdiSPV22i() {
        initComponents();
    }
     public mdiSPV22i(String titulo) {
        initComponents();
        this.setTitle(titulo);
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnCalculoTransformacion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFundamentosProgramacion = new javax.swing.JMenu();
        mfpHolaMundo = new javax.swing.JMenuItem();
        mfpEcuacionesLineales = new javax.swing.JMenuItem();
        mfpCalculoTransformacion = new javax.swing.JMenuItem();
        mfpSumaNumeros = new javax.swing.JMenuItem();
        mfpPromedioNotas = new javax.swing.JMenuItem();
        mfpSistemasCalculoAsistencia = new javax.swing.JMenuItem();
        mfpCalculoPromedio3Notas = new javax.swing.JMenuItem();
        mfpPelicula = new javax.swing.JMenuItem();
        mfpMiniEncuesta = new javax.swing.JMenuItem();
        mfpGeneradorNumeros = new javax.swing.JMenuItem();
        mfpImitador = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mPOOControlIngresoDocentes = new javax.swing.JMenuItem();
        mPOOControlParqueadero = new javax.swing.JMenuItem();
        mPOOEcuacionesLineales = new javax.swing.JMenuItem();
        mPOOIngresoUsuario = new javax.swing.JMenuItem();
        mPOOCalculadora = new javax.swing.JMenuItem();
        mPOOOperaciones2Numeros = new javax.swing.JMenuItem();
        mPOOImprimirPropiedades = new javax.swing.JMenuItem();
        mPOONominasEmpleados = new javax.swing.JMenuItem();
        mPOOSistemaCitasClinica = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        eSistemaNotas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mundo.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(120, 100));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sistema.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(120, 100));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        btnCalculoTransformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/convert-3217.png"))); // NOI18N
        btnCalculoTransformacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        btnCalculoTransformacion.setFocusable(false);
        btnCalculoTransformacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalculoTransformacion.setMaximumSize(new java.awt.Dimension(120, 100));
        btnCalculoTransformacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalculoTransformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoTransformacionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCalculoTransformacion);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("salir");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(120, 100));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setDoubleBuffered(true);
        jMenuBar1.setFocusCycleRoot(true);

        mFundamentosProgramacion.setBorder(null);
        mFundamentosProgramacion.setText("Fundamentos de programacion");
        mFundamentosProgramacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mFundamentosProgramacion.setMaximumSize(new java.awt.Dimension(400, 500));
        mFundamentosProgramacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFundamentosProgramacionActionPerformed(evt);
            }
        });

        mfpHolaMundo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpHolaMundo.setForeground(new java.awt.Color(204, 0, 0));
        mfpHolaMundo.setText("Hola mundo");
        mfpHolaMundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpHolaMundoActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpHolaMundo);

        mfpEcuacionesLineales.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpEcuacionesLineales.setText("Ecuaciones Lineales");
        mfpEcuacionesLineales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpEcuacionesLinealesActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpEcuacionesLineales);

        mfpCalculoTransformacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpCalculoTransformacion.setText("Calculo de Transformacion");
        mfpCalculoTransformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpCalculoTransformacionActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpCalculoTransformacion);

        mfpSumaNumeros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpSumaNumeros.setForeground(new java.awt.Color(204, 0, 0));
        mfpSumaNumeros.setText("Suma de numeros");
        mfpSumaNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpSumaNumerosActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpSumaNumeros);

        mfpPromedioNotas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpPromedioNotas.setText("Promedio de notas");
        mfpPromedioNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpPromedioNotasActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpPromedioNotas);

        mfpSistemasCalculoAsistencia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpSistemasCalculoAsistencia.setText("Sistema de calculo de asistencia");
        mfpSistemasCalculoAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpSistemasCalculoAsistenciaActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpSistemasCalculoAsistencia);

        mfpCalculoPromedio3Notas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpCalculoPromedio3Notas.setText("Calculo promedio de tres notas");
        mfpCalculoPromedio3Notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpCalculoPromedio3NotasActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpCalculoPromedio3Notas);

        mfpPelicula.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpPelicula.setText("Pelicula");
        mfpPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpPeliculaActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpPelicula);

        mfpMiniEncuesta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpMiniEncuesta.setText("Miniencuesta");
        mfpMiniEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpMiniEncuestaActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpMiniEncuesta);

        mfpGeneradorNumeros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpGeneradorNumeros.setText("Generador de numeros");
        mfpGeneradorNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpGeneradorNumerosActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpGeneradorNumeros);

        mfpImitador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mfpImitador.setText("Imitador");
        mfpImitador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfpImitadorActionPerformed(evt);
            }
        });
        mFundamentosProgramacion.add(mfpImitador);

        jMenuBar1.add(mFundamentosProgramacion);

        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        jMenu2.setText("Poo");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        mPOOControlIngresoDocentes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mPOOControlIngresoDocentes.setText("Control de ingresos de docentes");
        mPOOControlIngresoDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPOOControlIngresoDocentesActionPerformed(evt);
            }
        });
        jMenu2.add(mPOOControlIngresoDocentes);

        mPOOControlParqueadero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mPOOControlParqueadero.setText("Control de parqueo");
        mPOOControlParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPOOControlParqueaderoActionPerformed(evt);
            }
        });
        jMenu2.add(mPOOControlParqueadero);

        mPOOEcuacionesLineales.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mPOOEcuacionesLineales.setText("Ecuaciones de 2do grado");
        jMenu2.add(mPOOEcuacionesLineales);

        mPOOIngresoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mPOOIngresoUsuario.setText("Ingreso usuario");
        jMenu2.add(mPOOIngresoUsuario);

        mPOOCalculadora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mPOOCalculadora.setText("Calculadora");
        mPOOCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPOOCalculadoraActionPerformed(evt);
            }
        });
        jMenu2.add(mPOOCalculadora);

        mPOOOperaciones2Numeros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mPOOOperaciones2Numeros.setText("Operacion con 2  numeros");
        mPOOOperaciones2Numeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPOOOperaciones2NumerosActionPerformed(evt);
            }
        });
        jMenu2.add(mPOOOperaciones2Numeros);

        mPOOImprimirPropiedades.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mPOOImprimirPropiedades.setText("Imprimir propiedades de un vehiculo");
        mPOOImprimirPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPOOImprimirPropiedadesActionPerformed(evt);
            }
        });
        jMenu2.add(mPOOImprimirPropiedades);

        mPOONominasEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mPOONominasEmpleados.setText("Nominas de empleados");
        jMenu2.add(mPOONominasEmpleados);

        mPOOSistemaCitasClinica.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mPOOSistemaCitasClinica.setText("Sistema de citas-clinica");
        jMenu2.add(mPOOSistemaCitasClinica);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        jMenu3.setText("Evaluacion");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        eSistemaNotas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        eSistemaNotas.setText("Sistema de Notas");
        eSistemaNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSistemaNotasActionPerformed(evt);
            }
        });
        jMenu3.add(eSistemaNotas);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem1.setText("EXAMEN");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1247, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mPOOControlIngresoDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPOOControlIngresoDocentesActionPerformed
        jifrmControlIngresoDocente m=new jifrmControlIngresoDocente();
    panel.add(m);
        Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_mPOOControlIngresoDocentesActionPerformed

    private void mfpCalculoTransformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpCalculoTransformacionActionPerformed
    jifrmCalculoTransformacion m=new jifrmCalculoTransformacion();
    panel.add(m);
        Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_mfpCalculoTransformacionActionPerformed

    private void mPOOImprimirPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPOOImprimirPropiedadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPOOImprimirPropiedadesActionPerformed

    private void mfpHolaMundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpHolaMundoActionPerformed
//         jifrmHolaMundo obj = new  jifrmHolaMundo();
//         this.panel.add(obj);
//         obj.show();
         jifrmHolaMundo m = new jifrmHolaMundo();
        panel.add(m);
        Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_mfpHolaMundoActionPerformed

    private void mfpSumaNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpSumaNumerosActionPerformed
//    jifrmSumaNumeros obj = new  jifrmSumaNumeros();
//         this.panel.add(obj);
//         obj.show();  
        jifrmSumaNumeros m = new jifrmSumaNumeros();
        panel.add(m);
        Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
         
    }//GEN-LAST:event_mfpSumaNumerosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
         jifrmHolaMundo m = new jifrmHolaMundo();
        panel.add(m);
        Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jifrmSumaNumeros m = new jifrmSumaNumeros();
        panel.add(m);
        Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCalculoTransformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoTransformacionActionPerformed
      jifrmCalculoTransformacion m=new jifrmCalculoTransformacion();
    panel.add(m);
        Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_btnCalculoTransformacionActionPerformed

    private void mfpMiniEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpMiniEncuestaActionPerformed
     jifrmMiniEncuesta m=new jifrmMiniEncuesta();
    panel.add(m);
        Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();   // TODO add your handling code here:
    }//GEN-LAST:event_mfpMiniEncuestaActionPerformed

    private void mfpGeneradorNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpGeneradorNumerosActionPerformed
jifrmGeneradorNumeros m=new jifrmGeneradorNumeros();
        panel.add(m);
        Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_mfpGeneradorNumerosActionPerformed

    private void mfpImitadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpImitadorActionPerformed
jifrmImitador m=new jifrmImitador();
panel.add(m);
        Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_mfpImitadorActionPerformed

    private void mfpPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpPeliculaActionPerformed
jifrmPelicula m=new jifrmPelicula();
panel.add(m);
Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_mfpPeliculaActionPerformed

    private void mPOOCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPOOCalculadoraActionPerformed
jifrmCalculadora m=new jifrmCalculadora();
panel.add(m);
Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();

    }//GEN-LAST:event_mPOOCalculadoraActionPerformed

    private void mfpPromedioNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpPromedioNotasActionPerformed
jifrmPromedioNotas m=new jifrmPromedioNotas();
panel.add(m);
Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_mfpPromedioNotasActionPerformed

    private void mfpSistemasCalculoAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpSistemasCalculoAsistenciaActionPerformed
       jifrmSistemaCalculoAsistencia m=new jifrmSistemaCalculoAsistencia();
panel.add(m);
Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_mfpSistemasCalculoAsistenciaActionPerformed

    private void mfpCalculoPromedio3NotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpCalculoPromedio3NotasActionPerformed
        jifrmCalculoPromedio3Notas m=new jifrmCalculoPromedio3Notas();
panel.add(m);
Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_mfpCalculoPromedio3NotasActionPerformed

    private void mFundamentosProgramacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFundamentosProgramacionActionPerformed
       
    }//GEN-LAST:event_mFundamentosProgramacionActionPerformed

    private void eSistemaNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSistemaNotasActionPerformed
jifrmPromedioNotas m=new jifrmPromedioNotas();
panel.add(m);
Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();       
    }//GEN-LAST:event_eSistemaNotasActionPerformed

    private void mPOOControlParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPOOControlParqueaderoActionPerformed
jifrmcontrolParqueo m=new jifrmcontrolParqueo();
panel.add(m);
Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show(); 
    }//GEN-LAST:event_mPOOControlParqueaderoActionPerformed

    private void mfpEcuacionesLinealesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfpEcuacionesLinealesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mfpEcuacionesLinealesActionPerformed

    private void mPOOOperaciones2NumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPOOOperaciones2NumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPOOOperaciones2NumerosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     jifrmExamen m=new jifrmExamen();
     panel.add(m);
Dimension desktopSize = panel.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show(); 
 
                    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiSPV22i.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiSPV22i.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiSPV22i.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiSPV22i.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiSPV22i().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculoTransformacion;
    private javax.swing.JMenuItem eSistemaNotas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mFundamentosProgramacion;
    private javax.swing.JMenuItem mPOOCalculadora;
    private javax.swing.JMenuItem mPOOControlIngresoDocentes;
    private javax.swing.JMenuItem mPOOControlParqueadero;
    private javax.swing.JMenuItem mPOOEcuacionesLineales;
    private javax.swing.JMenuItem mPOOImprimirPropiedades;
    private javax.swing.JMenuItem mPOOIngresoUsuario;
    private javax.swing.JMenuItem mPOONominasEmpleados;
    private javax.swing.JMenuItem mPOOOperaciones2Numeros;
    private javax.swing.JMenuItem mPOOSistemaCitasClinica;
    private javax.swing.JMenuItem mfpCalculoPromedio3Notas;
    private javax.swing.JMenuItem mfpCalculoTransformacion;
    private javax.swing.JMenuItem mfpEcuacionesLineales;
    private javax.swing.JMenuItem mfpGeneradorNumeros;
    private javax.swing.JMenuItem mfpHolaMundo;
    private javax.swing.JMenuItem mfpImitador;
    private javax.swing.JMenuItem mfpMiniEncuesta;
    private javax.swing.JMenuItem mfpPelicula;
    private javax.swing.JMenuItem mfpPromedioNotas;
    private javax.swing.JMenuItem mfpSistemasCalculoAsistencia;
    private javax.swing.JMenuItem mfpSumaNumeros;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
